// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values
// do not exceed four million, find the sum of the even-valued terms.

var a = 0;
var b = 1;

for(c=1; c<4000000; c=d) {
    var d = c + b;
    var b = c;
    if(d%2===0) {
        var a = a + d;
    }
}
 
console.log(a);
